[package]
name = "bevy_dogoap"
version = "0.3.0"
edition = "2021"
description = "bevy_dogoap"
license = "MIT"
homepage = "https://github.com/victorb/dogoap"

[features]
default = ["compute-pool"]
compute-pool = []

[dependencies]
bevy = { version = "0.15", default-features = false, optional = false, features = [
    "wayland",
    "bevy_gizmos",
    "bevy_text",
    "multi_threaded",
    "default_font",
    "webgl2",
    "bevy_window",
] }
bevy-trait-query = { version = "0.7.0" }
dogoap = { path = "../dogoap", version = "0.3.0" }
dogoap_macros = { path = "../dogoap_macros", version = "0.3.0" }
rand = "0.8.5"
